apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-ms
spec:
  replicas: 3 # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: shipping-ms
  template:
    metadata:
      labels:
        app: shipping-ms
    spec:
      containers:
      - name: shipping-ms-container
        image: schets14/myimages:31 # Replace with your actual Docker image name and tag
        ports:
        - containerPort: 8080 # Replace with the port your application exposes
